default: &default
  adapter: postgresql
  encoding: unicode
  username: marceloverasalvatierra
  password: 1234
  pool: 5

development:
  <<: *default
  database: do_it_development
  port: 5433

test:
  <<: *default
  database: do_it_test
  port: 5433

production:
  <<: *default
  database: do_it_production
  username: ubuntu
  password: <%= ENV['NOMBRE_APP_DATABASE_PASSWORD'] %>
  port: 5432